# Generated by Django 2.0.6 on 2018-06-21 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='User ID')),
                ('EmployeeID', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='사번')),
                ('staffName', models.CharField(default='', max_length=10, verbose_name='이름')),
                ('emailAddress', models.EmailField(blank=True, editable=False, max_length=50, null=True, verbose_name='Email')),
                ('Department', models.CharField(blank=True, choices=[('Azure', 'Azure'), ('AWS', 'Amazon Cloud Service'), ('PM', 'Project Manager'), ('PMO', 'Project Manager Operation'), ('CDP', 'Cloud Data ')], max_length=50, null=True)),
                ('DepManager', models.BooleanField(default=False)),
                ('Title', models.CharField(choices=[('기타', '기타'), ('사원', '사원'), ('대리', '대리'), ('과장', '과장'), ('차장', '차장'), ('부장', '부장'), ('이사', '이사'), ('위원', '위원'), ('상무', '상무')], max_length=5, null=True)),
                ('HiringDate', models.DateField(default=django.utils.timezone.now)),
                ('LeaveDate', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('ManagerEmployee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
